CREATE DATABASE TESTE
GO

use teste
GO

create table JSON_FILES (
    id bigint primary key identity,
    JSONDATA nvarchar(max)
);

ALTER TABLE JSON_FILES
    ADD CONSTRAINT [Log record should be formatted as JSON]
                   CHECK (ISJSON(JSONDATA)=1)
GO

INSERT INTO JSON_FILES (JSONDATA)
VALUES ('[
    {
        "Name":  ".nuget",
        "FullName":  "C:\\Users\\sefonsec\\.nuget",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  ".nuget",
        "CreationTime":  "\/Date(1512574293675)\/",
        "CreationTimeUtc":  "\/Date(1512574293675)\/",
        "LastAccessTime":  "\/Date(1512574293675)\/",
        "LastAccessTimeUtc":  "\/Date(1512574293675)\/",
        "LastWriteTime":  "\/Date(1512574293675)\/",
        "LastWriteTimeUtc":  "\/Date(1512574293675)\/",
        "Attributes":  16,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.nuget",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".nuget",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-----",
        "BaseName":  ".nuget",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  ".sqlops",
        "FullName":  "C:\\Users\\sefonsec\\.sqlops",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  ".sqlops",
        "CreationTime":  "\/Date(1510825676471)\/",
        "CreationTimeUtc":  "\/Date(1510825676471)\/",
        "LastAccessTime":  "\/Date(1510825676472)\/",
        "LastAccessTimeUtc":  "\/Date(1510825676472)\/",
        "LastWriteTime":  "\/Date(1510825676472)\/",
        "LastWriteTimeUtc":  "\/Date(1510825676472)\/",
        "Attributes":  16,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.sqlops",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".sqlops",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-----",
        "BaseName":  ".sqlops",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "3D Objects",
        "FullName":  "C:\\Users\\sefonsec\\3D Objects",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1509144671082)\/",
        "CreationTimeUtc":  "\/Date(1509144671082)\/",
        "LastAccessTime":  "\/Date(1509144671082)\/",
        "LastAccessTimeUtc":  "\/Date(1509144671082)\/",
        "LastWriteTime":  "\/Date(1518648947889)\/",
        "LastWriteTimeUtc":  "\/Date(1518648947889)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\3D Objects",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "3D Objects",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "3D Objects",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Contacts",
        "FullName":  "C:\\Users\\sefonsec\\Contacts",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012185066)\/",
        "CreationTimeUtc":  "\/Date(1490012185066)\/",
        "LastAccessTime":  "\/Date(1490012185066)\/",
        "LastAccessTimeUtc":  "\/Date(1490012185066)\/",
        "LastWriteTime":  "\/Date(1518648948014)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948014)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Contacts",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Contacts",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Contacts",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Desktop",
        "FullName":  "C:\\Users\\sefonsec\\Desktop",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1518722214578)\/",
        "LastAccessTimeUtc":  "\/Date(1518722214578)\/",
        "LastWriteTime":  "\/Date(1518722214578)\/",
        "LastWriteTimeUtc":  "\/Date(1518722214578)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Desktop",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Desktop",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Desktop",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Documents",
        "FullName":  "C:\\Users\\sefonsec\\Documents",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1493387602005)\/",
        "LastAccessTimeUtc":  "\/Date(1493387602005)\/",
        "LastWriteTime":  "\/Date(1509144672488)\/",
        "LastWriteTimeUtc":  "\/Date(1509144672488)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Documents",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Documents",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Documents",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Downloads",
        "FullName":  "C:\\Users\\sefonsec\\Downloads",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1493029159505)\/",
        "CreationTimeUtc":  "\/Date(1493029159505)\/",
        "LastAccessTime":  "\/Date(1518790882466)\/",
        "LastAccessTimeUtc":  "\/Date(1518790882466)\/",
        "LastWriteTime":  "\/Date(1518790882466)\/",
        "LastWriteTimeUtc":  "\/Date(1518790882466)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Downloads",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Downloads",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Downloads",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Links",
        "FullName":  "C:\\Users\\sefonsec\\Links",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1518571905406)\/",
        "LastAccessTimeUtc":  "\/Date(1518571905406)\/",
        "LastWriteTime":  "\/Date(1518648948612)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948612)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Links",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Links",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Links",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Microsoft",
        "FullName":  "C:\\Users\\sefonsec\\Microsoft",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1492007595457)\/",
        "CreationTimeUtc":  "\/Date(1492007595457)\/",
        "LastAccessTime":  "\/Date(1518725163421)\/",
        "LastAccessTimeUtc":  "\/Date(1518725163421)\/",
        "LastWriteTime":  "\/Date(1518725163421)\/",
        "LastWriteTimeUtc":  "\/Date(1518725163421)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Microsoft",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Microsoft",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Microsoft",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Music",
        "FullName":  "C:\\Users\\sefonsec\\Music",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1492524221217)\/",
        "LastAccessTimeUtc":  "\/Date(1492524221217)\/",
        "LastWriteTime":  "\/Date(1518648948139)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948139)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Music",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Music",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Music",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "OneDrive",
        "FullName":  "C:\\Users\\sefonsec\\OneDrive",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012246963)\/",
        "CreationTimeUtc":  "\/Date(1490012246963)\/",
        "LastAccessTime":  "\/Date(1490012364547)\/",
        "LastAccessTimeUtc":  "\/Date(1490012364547)\/",
        "LastWriteTime":  "\/Date(1490012364547)\/",
        "LastWriteTimeUtc":  "\/Date(1490012364547)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\OneDrive",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "OneDrive",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "OneDrive",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "OneDrive - Microsoft",
        "FullName":  "C:\\Users\\sefonsec\\OneDrive - Microsoft",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012364547)\/",
        "CreationTimeUtc":  "\/Date(1490012364547)\/",
        "LastAccessTime":  "\/Date(1518725163286)\/",
        "LastAccessTimeUtc":  "\/Date(1518725163286)\/",
        "LastWriteTime":  "\/Date(1518725163287)\/",
        "LastWriteTimeUtc":  "\/Date(1518725163287)\/",
        "Attributes":  1073,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\OneDrive - Microsoft",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "OneDrive - Microsoft",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "dar--l",
        "BaseName":  "OneDrive - Microsoft",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Pictures",
        "FullName":  "C:\\Users\\sefonsec\\Pictures",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1506335576956)\/",
        "LastAccessTimeUtc":  "\/Date(1506335576956)\/",
        "LastWriteTime":  "\/Date(1518648948029)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948029)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Pictures",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Pictures",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Pictures",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Roaming",
        "FullName":  "C:\\Users\\sefonsec\\Roaming",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1492470736479)\/",
        "CreationTimeUtc":  "\/Date(1492470736479)\/",
        "LastAccessTime":  "\/Date(1492470736480)\/",
        "LastAccessTimeUtc":  "\/Date(1492470736480)\/",
        "LastWriteTime":  "\/Date(1492470736480)\/",
        "LastWriteTimeUtc":  "\/Date(1492470736480)\/",
        "Attributes":  16,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Roaming",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Roaming",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-----",
        "BaseName":  "Roaming",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Saved Games",
        "FullName":  "C:\\Users\\sefonsec\\Saved Games",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1490012185269)\/",
        "LastAccessTimeUtc":  "\/Date(1490012185269)\/",
        "LastWriteTime":  "\/Date(1518648948550)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948550)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Saved Games",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Saved Games",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Saved Games",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Searches",
        "FullName":  "C:\\Users\\sefonsec\\Searches",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012185160)\/",
        "CreationTimeUtc":  "\/Date(1490012185160)\/",
        "LastAccessTime":  "\/Date(1490012413578)\/",
        "LastAccessTimeUtc":  "\/Date(1490012413578)\/",
        "LastWriteTime":  "\/Date(1518648948123)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948123)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Searches",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Searches",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Searches",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Source",
        "FullName":  "C:\\Users\\sefonsec\\Source",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1505902222711)\/",
        "CreationTimeUtc":  "\/Date(1505902222711)\/",
        "LastAccessTime":  "\/Date(1505902222711)\/",
        "LastAccessTimeUtc":  "\/Date(1505902222711)\/",
        "LastWriteTime":  "\/Date(1505902222711)\/",
        "LastWriteTimeUtc":  "\/Date(1505902222711)\/",
        "Attributes":  16,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Source",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Source",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-----",
        "BaseName":  "Source",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  "Videos",
        "FullName":  "C:\\Users\\sefonsec\\Videos",
        "Parent":  {
                       "Name":  "sefonsec",
                       "FullName":  "C:\\Users\\sefonsec",
                       "Parent":  "Users",
                       "Exists":  true,
                       "Root":  "C:\\",
                       "Extension":  "",
                       "CreationTime":  "\/Date(1509142634332)\/",
                       "CreationTimeUtc":  "\/Date(1509142634332)\/",
                       "LastAccessTime":  "\/Date(1518042722707)\/",
                       "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                       "LastWriteTime":  "\/Date(1518042722707)\/",
                       "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                       "Attributes":  16
                   },
        "Exists":  true,
        "Root":  {
                     "Name":  "C:\\",
                     "FullName":  "C:\\",
                     "Parent":  null,
                     "Exists":  true,
                     "Root":  "C:\\",
                     "Extension":  "",
                     "CreationTime":  "\/Date(1468649064614)\/",
                     "CreationTimeUtc":  "\/Date(1468649064614)\/",
                     "LastAccessTime":  "\/Date(1518725161515)\/",
                     "LastAccessTimeUtc":  "\/Date(1518725161515)\/",
                     "LastWriteTime":  "\/Date(1518725161515)\/",
                     "LastWriteTimeUtc":  "\/Date(1518725161515)\/",
                     "Attributes":  22
                 },
        "Extension":  "",
        "CreationTime":  "\/Date(1490012156289)\/",
        "CreationTimeUtc":  "\/Date(1490012156289)\/",
        "LastAccessTime":  "\/Date(1492015137933)\/",
        "LastAccessTimeUtc":  "\/Date(1492015137933)\/",
        "LastWriteTime":  "\/Date(1518648948029)\/",
        "LastWriteTimeUtc":  "\/Date(1518648948029)\/",
        "Attributes":  17,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\Videos",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  "Videos",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  true,
        "Mode":  "d-r---",
        "BaseName":  "Videos",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  ".adalcache",
        "Length":  30680,
        "DirectoryName":  "C:\\Users\\sefonsec",
        "Directory":  {
                          "Name":  "sefonsec",
                          "FullName":  "C:\\Users\\sefonsec",
                          "Parent":  "Users",
                          "Exists":  true,
                          "Root":  "C:\\",
                          "Extension":  "",
                          "CreationTime":  "\/Date(1509142634332)\/",
                          "CreationTimeUtc":  "\/Date(1509142634332)\/",
                          "LastAccessTime":  "\/Date(1518042722707)\/",
                          "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                          "LastWriteTime":  "\/Date(1518042722707)\/",
                          "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                          "Attributes":  16
                      },
        "IsReadOnly":  false,
        "Exists":  true,
        "FullName":  "C:\\Users\\sefonsec\\.adalcache",
        "Extension":  ".adalcache",
        "CreationTime":  "\/Date(1504874336371)\/",
        "CreationTimeUtc":  "\/Date(1504874336371)\/",
        "LastAccessTime":  "\/Date(1504874336371)\/",
        "LastAccessTimeUtc":  "\/Date(1504874336371)\/",
        "LastWriteTime":  "\/Date(1518735865266)\/",
        "LastWriteTimeUtc":  "\/Date(1518735865266)\/",
        "Attributes":  32,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.adalcache",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".adalcache",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  false,
        "Mode":  "-a----",
        "VersionInfo":  {
                            "Comments":  null,
                            "CompanyName":  null,
                            "FileBuildPart":  0,
                            "FileDescription":  null,
                            "FileMajorPart":  0,
                            "FileMinorPart":  0,
                            "FileName":  "C:\\Users\\sefonsec\\.adalcache",
                            "FilePrivatePart":  0,
                            "FileVersion":  null,
                            "InternalName":  null,
                            "IsDebug":  false,
                            "IsPatched":  false,
                            "IsPrivateBuild":  false,
                            "IsPreRelease":  false,
                            "IsSpecialBuild":  false,
                            "Language":  null,
                            "LegalCopyright":  null,
                            "LegalTrademarks":  null,
                            "OriginalFilename":  null,
                            "PrivateBuild":  null,
                            "ProductBuildPart":  0,
                            "ProductMajorPart":  0,
                            "ProductMinorPart":  0,
                            "ProductName":  null,
                            "ProductPrivatePart":  0,
                            "ProductVersion":  null,
                            "SpecialBuild":  null,
                            "FileVersionRaw":  "0.0.0.0",
                            "ProductVersionRaw":  "0.0.0.0"
                        },
        "BaseName":  "",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  ".devaccounts",
        "Length":  3481,
        "DirectoryName":  "C:\\Users\\sefonsec",
        "Directory":  {
                          "Name":  "sefonsec",
                          "FullName":  "C:\\Users\\sefonsec",
                          "Parent":  "Users",
                          "Exists":  true,
                          "Root":  "C:\\",
                          "Extension":  "",
                          "CreationTime":  "\/Date(1509142634332)\/",
                          "CreationTimeUtc":  "\/Date(1509142634332)\/",
                          "LastAccessTime":  "\/Date(1518042722707)\/",
                          "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                          "LastWriteTime":  "\/Date(1518042722707)\/",
                          "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                          "Attributes":  16
                      },
        "IsReadOnly":  false,
        "Exists":  true,
        "FullName":  "C:\\Users\\sefonsec\\.devaccounts",
        "Extension":  ".devaccounts",
        "CreationTime":  "\/Date(1504874299376)\/",
        "CreationTimeUtc":  "\/Date(1504874299376)\/",
        "LastAccessTime":  "\/Date(1504874299376)\/",
        "LastAccessTimeUtc":  "\/Date(1504874299376)\/",
        "LastWriteTime":  "\/Date(1518698165544)\/",
        "LastWriteTimeUtc":  "\/Date(1518698165544)\/",
        "Attributes":  32,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.devaccounts",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".devaccounts",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  false,
        "Mode":  "-a----",
        "VersionInfo":  {
                            "Comments":  null,
                            "CompanyName":  null,
                            "FileBuildPart":  0,
                            "FileDescription":  null,
                            "FileMajorPart":  0,
                            "FileMinorPart":  0,
                            "FileName":  "C:\\Users\\sefonsec\\.devaccounts",
                            "FilePrivatePart":  0,
                            "FileVersion":  null,
                            "InternalName":  null,
                            "IsDebug":  false,
                            "IsPatched":  false,
                            "IsPrivateBuild":  false,
                            "IsPreRelease":  false,
                            "IsSpecialBuild":  false,
                            "Language":  null,
                            "LegalCopyright":  null,
                            "LegalTrademarks":  null,
                            "OriginalFilename":  null,
                            "PrivateBuild":  null,
                            "ProductBuildPart":  0,
                            "ProductMajorPart":  0,
                            "ProductMinorPart":  0,
                            "ProductName":  null,
                            "ProductPrivatePart":  0,
                            "ProductVersion":  null,
                            "SpecialBuild":  null,
                            "FileVersionRaw":  "0.0.0.0",
                            "ProductVersionRaw":  "0.0.0.0"
                        },
        "BaseName":  "",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  ".extaccounts",
        "Length":  0,
        "DirectoryName":  "C:\\Users\\sefonsec",
        "Directory":  {
                          "Name":  "sefonsec",
                          "FullName":  "C:\\Users\\sefonsec",
                          "Parent":  "Users",
                          "Exists":  true,
                          "Root":  "C:\\",
                          "Extension":  "",
                          "CreationTime":  "\/Date(1509142634332)\/",
                          "CreationTimeUtc":  "\/Date(1509142634332)\/",
                          "LastAccessTime":  "\/Date(1518042722707)\/",
                          "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                          "LastWriteTime":  "\/Date(1518042722707)\/",
                          "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                          "Attributes":  16
                      },
        "IsReadOnly":  false,
        "Exists":  true,
        "FullName":  "C:\\Users\\sefonsec\\.extaccounts",
        "Extension":  ".extaccounts",
        "CreationTime":  "\/Date(1504874299382)\/",
        "CreationTimeUtc":  "\/Date(1504874299382)\/",
        "LastAccessTime":  "\/Date(1504874299382)\/",
        "LastAccessTimeUtc":  "\/Date(1504874299382)\/",
        "LastWriteTime":  "\/Date(1504874299382)\/",
        "LastWriteTimeUtc":  "\/Date(1504874299382)\/",
        "Attributes":  32,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.extaccounts",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".extaccounts",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  false,
        "Mode":  "-a----",
        "VersionInfo":  {
                            "Comments":  null,
                            "CompanyName":  null,
                            "FileBuildPart":  0,
                            "FileDescription":  null,
                            "FileMajorPart":  0,
                            "FileMinorPart":  0,
                            "FileName":  "C:\\Users\\sefonsec\\.extaccounts",
                            "FilePrivatePart":  0,
                            "FileVersion":  null,
                            "InternalName":  null,
                            "IsDebug":  false,
                            "IsPatched":  false,
                            "IsPrivateBuild":  false,
                            "IsPreRelease":  false,
                            "IsSpecialBuild":  false,
                            "Language":  null,
                            "LegalCopyright":  null,
                            "LegalTrademarks":  null,
                            "OriginalFilename":  null,
                            "PrivateBuild":  null,
                            "ProductBuildPart":  0,
                            "ProductMajorPart":  0,
                            "ProductMinorPart":  0,
                            "ProductName":  null,
                            "ProductPrivatePart":  0,
                            "ProductVersion":  null,
                            "SpecialBuild":  null,
                            "FileVersionRaw":  "0.0.0.0",
                            "ProductVersionRaw":  "0.0.0.0"
                        },
        "BaseName":  "",
        "Target":  [

                   ],
        "LinkType":  null
    },
    {
        "Name":  ".gitconfig",
        "Length":  62,
        "DirectoryName":  "C:\\Users\\sefonsec",
        "Directory":  {
                          "Name":  "sefonsec",
                          "FullName":  "C:\\Users\\sefonsec",
                          "Parent":  "Users",
                          "Exists":  true,
                          "Root":  "C:\\",
                          "Extension":  "",
                          "CreationTime":  "\/Date(1509142634332)\/",
                          "CreationTimeUtc":  "\/Date(1509142634332)\/",
                          "LastAccessTime":  "\/Date(1518042722707)\/",
                          "LastAccessTimeUtc":  "\/Date(1518042722707)\/",
                          "LastWriteTime":  "\/Date(1518042722707)\/",
                          "LastWriteTimeUtc":  "\/Date(1518042722707)\/",
                          "Attributes":  16
                      },
        "IsReadOnly":  false,
        "Exists":  true,
        "FullName":  "C:\\Users\\sefonsec\\.gitconfig",
        "Extension":  ".gitconfig",
        "CreationTime":  "\/Date(1495462118357)\/",
        "CreationTimeUtc":  "\/Date(1495462118357)\/",
        "LastAccessTime":  "\/Date(1495462118396)\/",
        "LastAccessTimeUtc":  "\/Date(1495462118396)\/",
        "LastWriteTime":  "\/Date(1495462118399)\/",
        "LastWriteTimeUtc":  "\/Date(1495462118399)\/",
        "Attributes":  32,
        "PSPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec\\.gitconfig",
        "PSParentPath":  "Microsoft.PowerShell.Core\\FileSystem::C:\\Users\\sefonsec",
        "PSChildName":  ".gitconfig",
        "PSDrive":  {
                        "CurrentLocation":  "Users\\sefonsec",
                        "Name":  "C",
                        "Provider":  "Microsoft.PowerShell.Core\\FileSystem",
                        "Root":  "C:\\",
                        "Description":  "OSDisk",
                        "MaximumSize":  null,
                        "Credential":  "System.Management.Automation.PSCredential",
                        "DisplayRoot":  null
                    },
        "PSProvider":  {
                           "ImplementingType":  "Microsoft.PowerShell.Commands.FileSystemProvider",
                           "HelpFile":  "System.Management.Automation.dll-Help.xml",
                           "Name":  "FileSystem",
                           "PSSnapIn":  "Microsoft.PowerShell.Core",
                           "ModuleName":  "Microsoft.PowerShell.Core",
                           "Module":  null,
                           "Description":  "",
                           "Capabilities":  52,
                           "Home":  "C:\\Users\\sefonsec",
                           "Drives":  "C"
                       },
        "PSIsContainer":  false,
        "Mode":  "-a----",
        "VersionInfo":  {
                            "Comments":  null,
                            "CompanyName":  null,
                            "FileBuildPart":  0,
                            "FileDescription":  null,
                            "FileMajorPart":  0,
                            "FileMinorPart":  0,
                            "FileName":  "C:\\Users\\sefonsec\\.gitconfig",
                            "FilePrivatePart":  0,
                            "FileVersion":  null,
                            "InternalName":  null,
                            "IsDebug":  false,
                            "IsPatched":  false,
                            "IsPrivateBuild":  false,
                            "IsPreRelease":  false,
                            "IsSpecialBuild":  false,
                            "Language":  null,
                            "LegalCopyright":  null,
                            "LegalTrademarks":  null,
                            "OriginalFilename":  null,
                            "PrivateBuild":  null,
                            "ProductBuildPart":  0,
                            "ProductMajorPart":  0,
                            "ProductMinorPart":  0,
                            "ProductName":  null,
                            "ProductPrivatePart":  0,
                            "ProductVersion":  null,
                            "SpecialBuild":  null,
                            "FileVersionRaw":  "0.0.0.0",
                            "ProductVersionRaw":  "0.0.0.0"
                        },
        "BaseName":  "",
        "Target":  [

                   ],
        "LinkType":  null
    }
]')

GO
SELECT *
FROM OPENJSON( (SELECT JSONDATA FROM JSON_FILES where id = 1), '$.Name')

GO
SELECT *
FROM OPENJSON( 
	(SELECT JSONDATA FROM JSON_FILES where id = 1)
)
WITH (   
              Name varchar(200)   '$.Name',
			  FullName varchar(200)   '$.FullName'
)  

SELECT JSON_VALUE(JSONDATA, '$[0].Name'),* FROM JSON_FILES