SET NOCOUNT ON

DECLARE @COMMAND AS NVARCHAR(MAX)
DECLARE @DBNAME AS VARCHAR(255)
DECLARE @FILENAME AS VARCHAR(255)

IF OBJECT_ID('tempdb..#TEMP_DATABASES') IS NOT NULL
	DROP TABLE #TEMP_DATABASES

SELECT [NAME]
INTO #TEMP_DATABASES
FROM sys.databases
WHERE RECOVERY_MODEL_DESC = 'SIMPLE'
ORDER BY [NAME]

WHILE (SELECT COUNT(*) FROM #TEMP_DATABASES) > 0
BEGIN
	SELECT TOP 1 @DBNAME = [NAME] FROM #TEMP_DATABASES	

	SET @COMMAND = 'SELECT @FILENAME = [Name] FROM '+ @DBNAME + '.sys.sysfiles WHERE GROUPID = 0'
	EXECUTE sp_executesql @COMMAND, N'@FILENAME VARCHAR(255) OUTPUT', @FILENAME OUTPUT
	
	SELECT @DBNAME,@FILENAME

	SET @COMMAND = 'USE ' + @DBNAME + '; DBCC SHRINKFILE (N''' + @FILENAME + ''' , 0, TRUNCATEONLY)'
	EXEC (@COMMAND)
	--PRINT (@COMMAND)

	DELETE FROM #TEMP_DATABASES WHERE [NAME] = @DBNAME

END